services:
  auth_service_db:
    image: mariadb:12.2.2@sha256:b3af559fc38e013c50dd5b5993bfbbb21125c1a62d976b3b0a14d9c4acaae578
    volumes:
      - ./init-db/:/docker-entrypoint-initdb.d/
      - ./.data/mysql/:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: auth_service_user
      MYSQL_PASSWORD: auth_service_pw
    ports:
      - "3306:3306"
    networks:
      - auth_service_db
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  auth_service_db_migration:
    image: arigaio/atlas:1.1.6-community-alpine@sha256:b7477e7e81344f29e731bb38ffe1b4f28e4dd53463b6eceb5e51b62719b28ca9
    command: >
      schema apply
      --auto-approve
      --url "maria://auth_service_user:auth_service_pw@auth_service_db:3306/auth_service_db"
      --to file:///schema/schema.sql
      --dev-url "maria://auth_service_user:auth_service_pw@auth_service_db:3306/auth_service_dev"
    networks:
      - auth_service_db
    depends_on:
      auth_service_db:
        condition: service_healthy
    volumes:
      - ../schema/database:/schema
  auth_service_http:
    image: auth_service_http:latest
    ports:
      - "3000:3000"
    networks:
      - auth_service_db
    depends_on:
      auth_service_db:
        condition: service_healthy
    environment:
      AUTH_SERVICE_DB_HOST: auth_service_db
      AUTH_SERVICE_DB_PORT: 3306
      AUTH_SERVICE_DB_USER: auth_service_user
      AUTH_SERVICE_DB_PASSWORD: auth_service_pw
      AUTH_SERVICE_DB_NAME: auth_service_db
      AUTH_SERVICE_HTTP_PORT: 3000
    env_file: "http-server.env"

networks:
  auth_service_db:
    driver: bridge
