// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_log.sql

package queries

import (
	"context"
	"time"
)

const insertAccessLog = `-- name: InsertAccessLog :exec
INSERT INTO users_access_logs (user_id, action_type, login_id, ip, user_agent, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAccessLogParams struct {
	UserID     int32     `db:"user_id"`
	ActionType int8      `db:"action_type"`
	LoginID    []byte    `db:"login_id"`
	Ip         []byte    `db:"ip"`
	UserAgent  string    `db:"user_agent"`
	CreatedAt  time.Time `db:"created_at"`
}

func (q *Queries) InsertAccessLog(ctx context.Context, arg InsertAccessLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAccessLog,
		arg.UserID,
		arg.ActionType,
		arg.LoginID,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}
