// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package queries

import (
	"context"
	"time"
)

const deleteLoginKey = `-- name: DeleteLoginKey :exec
DELETE
FROM users_login_key
WHERE user_id = ?
`

func (q *Queries) DeleteLoginKey(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteLoginKey, userID)
	return err
}

const deleteUserSubBySub = `-- name: DeleteUserSubBySub :exec
DELETE
FROM users_sub
WHERE sub = ?
`

func (q *Queries) DeleteUserSubBySub(ctx context.Context, sub string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSubBySub, sub)
	return err
}

const getUserIDByLoginKey = `-- name: GetUserIDByLoginKey :one
SELECT user_id
FROM users_login_key
WHERE login_key = ?
`

func (q *Queries) GetUserIDByLoginKey(ctx context.Context, loginKey int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByLoginKey, loginKey)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserIDBySub = `-- name: GetUserIDBySub :one
SELECT user_id
FROM users_sub
WHERE sub = ?
`

func (q *Queries) GetUserIDBySub(ctx context.Context, sub string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserIDBySub, sub)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const insertLoginKeyForUserID = `-- name: InsertLoginKeyForUserID :exec
INSERT INTO users_login_key (user_id, login_key, created_at)
VALUES (?, ?, ?)
`

type InsertLoginKeyForUserIDParams struct {
	UserID    int32     `db:"user_id"`
	LoginKey  int64     `db:"login_key"`
	CreatedAt time.Time `db:"created_at"`
}

func (q *Queries) InsertLoginKeyForUserID(ctx context.Context, arg InsertLoginKeyForUserIDParams) error {
	_, err := q.db.ExecContext(ctx, insertLoginKeyForUserID, arg.UserID, arg.LoginKey, arg.CreatedAt)
	return err
}

const insertSubForUserID = `-- name: InsertSubForUserID :execrows
INSERT IGNORE INTO users_sub (user_id, sub, created_at)
VALUES (?, ?, ?)
`

type InsertSubForUserIDParams struct {
	UserID    int32     `db:"user_id"`
	Sub       string    `db:"sub"`
	CreatedAt time.Time `db:"created_at"`
}

func (q *Queries) InsertSubForUserID(ctx context.Context, arg InsertSubForUserIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSubForUserID, arg.UserID, arg.Sub, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
