// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"
)

type User struct {
	ID        int32     `db:"id"`
	Uuid      []byte    `db:"uuid"`
	CreatedAt time.Time `db:"created_at"`
}

type UsersAccessLog struct {
	ID         int64     `db:"id"`
	UserID     int32     `db:"user_id"`
	ActionType int8      `db:"action_type"`
	LoginID    []byte    `db:"login_id"`
	Ip         []byte    `db:"ip"`
	UserAgent  string    `db:"user_agent"`
	CreatedAt  time.Time `db:"created_at"`
}

type UsersAccessToken struct {
	ID             int64     `db:"id"`
	RefreshTokenID int64     `db:"refresh_token_id"`
	Jti            []byte    `db:"jti"`
	CreatedAt      time.Time `db:"created_at"`
}

type UsersLoginKey struct {
	UserID    int32     `db:"user_id"`
	LoginKey  int64     `db:"login_key"`
	CreatedAt time.Time `db:"created_at"`
}

type UsersRefreshToken struct {
	ID        int64     `db:"id"`
	UserID    int32     `db:"user_id"`
	Jti       []byte    `db:"jti"`
	LoginID   []byte    `db:"login_id"`
	CreatedAt time.Time `db:"created_at"`
}

type UsersSub struct {
	UserID    int32     `db:"user_id"`
	Sub       string    `db:"sub"`
	CreatedAt time.Time `db:"created_at"`
}
