name: Image build for App
on:
  push:
    paths:
      - '.github/workflows/image_build_app.yml'
      - 'app/**'
      - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd: ["http-server"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Set up Go"
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: app/go.mod
          cache: true
          cache-dependency-path: |
            app/go.sum
      - name: "Build"
        working-directory: docker
        run: make build-${{ matrix.cmd }}
